version: '3.4'

services:
  webapp:
    build:
      context: ./
      dockerfile: ./Integration/Dockerfile
    deploy:
      mode: replicated
      replicas: 10
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - ~/.aspnet/https:/https:ro
    depends_on:
      - cache
  cache:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'